const C=window.SPARK_CONFIG||{API_URL:"",POLL_MS:3500,GROUPS:["1","2","3","4","5","6"]};
const D=window.SPARK_DATA;
const STAGES=[
 {id:1,title:"Starting Record & Individual First Impression",mins:4},
 {id:2,title:"Need to Know",mins:6},
 {id:3,title:"Choose What to Investigate",mins:5},
 {id:4,title:"Review the Evidence",mins:8},
 {id:5,title:"Preliminary Group Recommendation",mins:7},
 {id:6,title:"Evolving Information Update",mins:5},
 {id:7,title:"Perspective Challenge",mins:6},
 {id:8,title:"Final Decision, Conditions & Reconsideration",mins:8},
 {id:9,title:"Reflection & Co-Design",mins:18},
 {id:10,title:"Transfer to Existing Instruction",mins:25}
];
const q=new URLSearchParams(location.search);
let session={role:window.SPARK_BOOT?.role||q.get('role')||'participant',participant:'',group:window.SPARK_BOOT?.group||q.get('group')||'1',recorder:false};
let server={stage:1,deadline:null,prompt:"",selectedEvidence:[],votes:{},groupData:{},participants:[],ready:[]};
let pollHandle=null,timerHandle=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c])),now=()=>Date.now();
function appsScriptEnabled(){return !!window.SPARK_APPS_SCRIPT&&typeof google!=="undefined"&&google.script&&google.script.run}
function apiEnabled(){return appsScriptEnabled()||!!C.API_URL}
function gas(action,payload={}){return new Promise((resolve,reject)=>google.script.run.withSuccessHandler(resolve).withFailureHandler(e=>reject(new Error(e?.message||e))).api(action,payload))}
async function callApi(action,payload={}){if(appsScriptEnabled())return gas(action,payload);if(C.API_URL){const r=await fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action,...payload}),redirect:'follow'});if(!r.ok)throw new Error(`Backend ${r.status}`);return r.json()}return demoApi(action,payload)}
function demoKey(){return 'spark_workshop_demo_v3'}
function demoLoad(){return JSON.parse(localStorage.getItem(demoKey())||'{}')}
function demoSave(x){localStorage.setItem(demoKey(),JSON.stringify(x))}
async function demoApi(action,payload){const d=demoLoad();d.state=d.state||{stage:1,deadline:null,prompt:"",selectedEvidenceByGroup:{},votes:{},groupData:{},participants:{},ready:{},events:[]};const s=d.state;if(action==='join'){s.participants[payload.participant]=payload;s.events.push({type:'join',ts:now(),...payload})}else if(action==='event'){s.events.push({...payload,ts:now()})}else if(action==='submit'){const g=payload.group;s.groupData[g]=s.groupData[g]||{};s.groupData[g][payload.key]=payload.value;s.events.push({type:'submit',ts:now(),...payload})}else if(action==='vote'){const g=payload.group;s.votes[g]=s.votes[g]||{};s.votes[g][`s${payload.stage}`]=s.votes[g][`s${payload.stage}`]||{};s.votes[g][`s${payload.stage}`][payload.participant]={choice:payload.choice,confidence:payload.confidence,ts:now()}}else if(action==='selectEvidence'){s.selectedEvidenceByGroup[payload.group]=payload.ids;s.events.push({type:'evidence_selected',ts:now(),...payload})}else if(action==='ready'){s.ready[payload.group]=s.ready[payload.group]||[];if(!s.ready[payload.group].includes(payload.participant))s.ready[payload.group].push(payload.participant)}else if(action==='facilitator'){Object.assign(s,payload.patch);if(payload.patch.stage){s.prompt='';s.deadline=now()+((STAGES[payload.patch.stage-1]?.mins||5)*60000)}}demoSave(d);if(action==='state')return{ok:true,state:{stage:s.stage,deadline:s.deadline,prompt:s.prompt,selectedEvidence:s.selectedEvidenceByGroup[payload.group]||[],votes:s.votes[payload.group]||{},groupData:s.groupData[payload.group]||{},participants:Object.values(s.participants).filter(p=>p.group===payload.group),ready:s.ready[payload.group]||[]}};if(action==='allState')return{ok:true,data:s};return{ok:true}}
function decisionChoices(name){return `<div class="choice-grid">${D.decisions.map(x=>`<label class="choice"><input type="radio" name="${name}" value="${esc(x)}"><span>${esc(x)}</span></label>`).join('')}</div>`}
function confidence(id){return `<label>Confidence<div class="range-row"><input id="${id}" type="range" min="0" max="100" value="50"><span class="confidence-value" id="${id}v">50 / 100</span></div></label>`}
function recorderOnly(html){return session.recorder?html:`<div class="callout"><strong>Group recorder:</strong> Discuss together. The recorder enters the group's artifact.</div>`}
function tableRows(prefix,cols,rows=4){return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${Array.from({length:rows},(_,r)=>`<tr>${cols.map((_,c)=>`<td><textarea data-key="${prefix}_${r}_${c}"></textarea></td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function evidenceLegend(){return `<div class="source-note"><span class="provenance p1">PUBLIC RECORD</span> official agreement/city/utility/planning material &nbsp; <span class="provenance p2">LATER REPORTING</span> current reported update &nbsp; <span class="provenance unresolved">UNRESOLVED</span> legitimate missing information</div>`}
function evidenceCard(id){const e=D.evidence[id];return `<article class="evidence-card"><h4>${id}. ${esc(e.title)}</h4>${evidenceLegend()}<strong>What the current record says</strong><ul>${e.facts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><strong>What this packet still does not answer</strong><ul>${e.unknowns.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="source-note"><strong>Source status:</strong> ${esc(e.source)}</div></article>`}
function selectedEvidenceHtml(){const ids=server.selectedEvidence||[];return ids.length?`<div class="evidence-grid">${ids.map(evidenceCard).join('')}</div>`:`<div class="callout">No evidence packets have been released yet.</div>`}
function stakeholderHtml(){return `<details><summary>Who could be affected by this decision?</summary><div class="stakeholders">${D.stakeholders.map(x=>`<span class="stakeholder">${esc(x)}</span>`).join('')}</div><p class="muted">You are not assigned a stakeholder role. This is context, not a checklist.</p></details>`}
function voteDistribution(votes){const out=Object.fromEntries(D.decisions.map(x=>[x,0]));Object.values(votes||{}).forEach(v=>{if(out[v.choice]!==undefined)out[v.choice]++});return out}
function voteSummaryHtml(votes){const total=Object.keys(votes||{}).length;if(!total)return `<div class="card compact"><p class="muted">No participant choices submitted yet.</p></div>`;const dist=voteDistribution(votes),max=Math.max(...Object.values(dist)),wins=D.decisions.filter(x=>dist[x]===max&&max>0),label=max===total?'Consensus':wins.length===1?'Majority':'No majority / tie';return `<div class="card compact"><div class="eyebrow">Current group result</div><p><strong>${label}:</strong> ${esc(wins.join(' / '))} (${max} of ${total})</p><div class="vote-bars">${D.decisions.map(x=>`<div class="vote-row"><span>${esc(x)}</span><div class="bar"><span style="width:${dist[x]/total*100}%"></span></div><b>${dist[x]}</b></div>`).join('')}</div></div>`}
function stageHtml(n){
 if(n===1)return `<section class="card stage-card"><h3>Your role</h3><p>You are members of a Community Advisory Team advising local leaders whether, and under what conditions, the community should support a proposed hyperscale data-center campus in a growing Central Arkansas community.</p>${stakeholderHtml()}<div class="instruction">Treat the information below as the <strong>current project record</strong>. It is not necessarily complete. You may question meaning, sufficiency, assumptions, source quality and what still needs verification.</div><div class="facts">${D.startingFacts.map(x=>`<div class="fact">${esc(x)}</div>`).join('')}</div></section><section class="card stage-card"><h3>Individual first impression</h3><p class="muted">Read the starting record before submitting. Submit before discussing your recommendation with the group.</p>${decisionChoices('s1decision')}${confidence('s1conf')}<label>Two or three factors most important to your recommendation<textarea id="s1factors"></textarea></label><label>Most important thing you still need to know or verify<textarea id="s1unknown"></textarea></label><button class="primary submit-vote" data-stage="1">Submit individual response</button></section>`;
 if(n===2)return `<section class="card stage-card"><h3>Map uncertainty</h3><p>Compare questions and concerns. Distinguish supplied evidence from claims or assumptions that still need verification.</p>${recorderOnly(tableRows('ntk',["Evidence we currently have","What we need to know / verify","How or where could we find out?"],5)+`<label>Which 2–3 unanswered questions could most change the group's recommendation?<textarea id="priorityUnknowns"></textarea></label><button class="primary group-submit" data-key="stage2">Save group Need-to-Know</button>`)}</section>`;
 if(n===3)return `<section class="card stage-card"><h3>Choose only TWO evidence packets</h3><p>Choose based on what could change or sharpen the decision, not merely what sounds interesting.</p>${recorderOnly(`<div class="evidence-grid">${Object.entries(D.evidence).map(([id,e])=>`<label class="evidence-card evidence-select"><input type="checkbox" name="evidence" value="${id}"><span><strong>${id}. ${esc(e.title)}</strong><br><span class="muted">${esc(e.unknowns[0])}</span></span></label>`).join('')}</div><label>Why these two?<textarea id="evidenceWhy"></textarea></label><label>What questions do you hope they answer?<textarea id="evidenceQuestions"></textarea></label><button class="primary" id="selectEvidenceBtn">Lock evidence selection</button>`)}</section>`;
 if(n===4)return `<section class="card stage-card"><h3>Review the evidence</h3><p>Focus on what the evidence actually resolves, what it complicates and what remains uncertain.</p>${selectedEvidenceHtml()}</section><section class="card stage-card">${recorderOnly(tableRows('review',["Packet","What did it help answer?","What remains uncertain / needs verification?","How useful was it to the decision?"],2)+`<label>Did the evidence create any new important question?<textarea id="newQuestion"></textarea></label><button class="primary group-submit" data-key="stage4">Save evidence review</button>`)}</section>`;
 if(n===5)return `<section class="card stage-card"><h3>Preliminary group recommendation</h3><p>Discuss first. Then <strong>every participant</strong> submits a choice. Unanimous selections are consensus; otherwise the distribution is preserved and the majority is identified. Ties remain unresolved.</p>${decisionChoices('s5decision')}${confidence('s5conf')}<button class="primary submit-vote" data-stage="5">Submit my preliminary choice</button></section>${voteSummaryHtml(server.votes?.s5||{})}<section class="card stage-card">${recorderOnly(`<label>Evidence that matters most<textarea id="s5evidence"></textarea></label><label>Why it matters / group reasoning<textarea id="s5reasoning"></textarea></label><label>Most important remaining uncertainty<textarea id="s5uncertainty"></textarea></label><label>Strongest dissenting rationale, if any<textarea id="s5dissent"></textarea></label><button class="primary group-submit" data-key="stage5">Save group reasoning</button>`)}</section>`;
 if(n===6)return `<section class="card stage-card"><h3>Evolving information update</h3><div class="instruction">Several months later, additional information becomes available. Some uncertainty is reduced while other uncertainty grows.</div><div class="facts">${D.stage6Update.map(x=>`<div class="fact">${esc(x)}</div>`).join('')}</div><p><strong>Does this strengthen, weaken, or leave unchanged your recommendation?</strong> You are not expected to change your position.</p>${decisionChoices('s6decision')}${confidence('s6conf')}<label>What changed in your reasoning, or why did your reasoning remain stable?<textarea id="s6why"></textarea></label><label>What new or persistent uncertainty matters most now?<textarea id="s6unknown"></textarea></label><button class="primary submit-vote" data-stage="6">Submit my updated choice</button></section>${voteSummaryHtml(server.votes?.s6||{})}`;
 if(n===7)return `<section class="card stage-card"><h3>Perspective challenge</h3><p>Using only the evidence already available, construct the strongest defensible case for one plausible alternative to the group's current recommendation. You do not have to agree with it.</p>${recorderOnly(`<label>Alternative recommendation<select id="altChoice"><option value="">Choose...</option>${D.decisions.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Evidence that supports this alternative<textarea id="altEvidence"></textarea></label><label>Which stakeholder interest or risk does it take more seriously?<textarea id="altStakeholder"></textarea></label><label>What assumptions or enforceable conditions would have to be true?<textarea id="altConditions"></textarea></label><label>What is strongest about this alternative?<textarea id="altStrongest"></textarea></label><button class="primary group-submit" data-key="stage7">Save perspective challenge</button>`)}</section>`;
 if(n===8)return `<section class="card stage-card"><h3>Final individual choice</h3><p>After the evidence update and perspective challenge, every participant submits a final choice.</p>${decisionChoices('s8decision')}${confidence('s8conf')}<button class="primary submit-vote" data-stage="8">Submit my final choice</button></section>${voteSummaryHtml(server.votes?.s8||{})}<section class="card stage-card">${recorderOnly(`<h3>Make the decision implementable</h3><p>If the group favors Proceed / Proceed with conditions, identify 2–4 enforceable conditions. If it favors Defer / Oppose, identify what evidence or change could reopen the decision.</p>${tableRows('cond',["Condition / trigger","How measured or verified?","Who reports / enforces?","What happens if unmet?"],3)}<label>What future evidence/event/condition would make the group reconsider?<textarea id="reconsider"></textarea></label><label>What new information would NOT be enough by itself?<textarea id="notEnough"></textarea></label><label>Strongest dissenting rationale, if any<textarea id="finalDissent"></textarea></label><button class="primary group-submit" data-key="stage8">Save final group artifact</button>`)}</section>`;
 if(n===9)return `<section class="card stage-card"><h3>Reflection & co-design</h3><p>Now step out of the scenario and evaluate the experience as educators.</p>${recorderOnly(`<label>Authenticity & usability: What felt realistic or artificial? What must change?<textarea id="rAuthenticity"></textarea></label><label>Reasoning opportunities: Where did meaningful reasoning happen? What emerged without being explicitly prompted?<textarea id="rReasoning"></textarea></label><label>Scaffolds & cognitive load: What helped, constrained, led or confused?<textarea id="rScaffolds"></textarea></label><label>Observability: What student work or behavior could a teacher realistically collect or observe?<textarea id="rObservable"></textarea></label><button class="primary group-submit" data-key="stage9">Save reflection</button>`)}</section>`;
 if(n===10)return `<section class="card stage-card"><h3>Transfer to existing instruction</h3><p>Identify one activity you already use and apply the same reasoning-opportunity lens.</p>${recorderOnly(`<label>Existing activity<textarea id="tActivity"></textarea></label><label>Consequential judgment or decision students make<textarea id="tDecision"></textarea></label><label>What is uncertain / incomplete?<textarea id="tUncertainty"></textarea></label><label>What evidence could matter?<textarea id="tEvidence"></textarea></label><label>Minimal change that could strengthen the reasoning opportunity<textarea id="tMinimal"></textarea></label><label>What could a teacher realistically observe?<textarea id="tObserve"></textarea></label><label>Where else could the same reasoning pattern transfer?<textarea id="tTransfer"></textarea></label><button class="primary group-submit" data-key="stage10">Save transfer map</button>`)}</section>`;
 return '';
}
function collectScope(scope){const v={};scope.querySelectorAll('textarea[data-key]').forEach(el=>v[el.dataset.key]=el.value);scope.querySelectorAll('textarea[id],input[id],select[id]').forEach(el=>{if(!['radio','checkbox','button'].includes(el.type))v[el.id]=el.value});return v}
function wireStage(){document.querySelectorAll('input[type=range]').forEach(x=>x.oninput=()=>$('#'+x.id+'v').textContent=`${x.value} / 100`);document.querySelectorAll('.submit-vote').forEach(b=>b.onclick=async()=>{const st=+b.dataset.stage,choice=document.querySelector(`input[name=s${st}decision]:checked`)?.value;if(!choice)return alert('Choose a recommendation first.');const conf=+($(`#s${st}conf`)?.value||50);await callApi('vote',{group:session.group,participant:session.participant,stage:st,choice,confidence:conf});if(st===1)await callApi('submit',{group:session.group,participant:session.participant,key:`s1_${session.participant}`,value:{factors:$('#s1factors').value,unknown:$('#s1unknown').value}});if(st===6)await callApi('submit',{group:session.group,participant:session.participant,key:`s6_${session.participant}`,value:{why:$('#s6why').value,unknown:$('#s6unknown').value}});setSaved('Submitted');await refreshState()});document.querySelectorAll('.group-submit').forEach(b=>b.onclick=async()=>{if(!session.recorder)return;await callApi('submit',{group:session.group,participant:session.participant,key:b.dataset.key,value:collectScope(b.closest('section'))});setSaved('Group response saved')});$('#selectEvidenceBtn')?.addEventListener('click',async()=>{const ids=[...document.querySelectorAll('input[name=evidence]:checked')].map(x=>x.value);if(ids.length!==2)return alert('Choose exactly two evidence packets.');await callApi('selectEvidence',{group:session.group,participant:session.participant,ids});await callApi('submit',{group:session.group,participant:session.participant,key:'stage3',value:{ids,why:$('#evidenceWhy').value,questions:$('#evidenceQuestions').value}});setSaved('Evidence selection locked');await refreshState()});$('#readyBtn')?.addEventListener('click',async()=>{await callApi('ready',{group:session.group,participant:session.participant,stage:server.stage});setSaved('Ready status sent')})}
function setSaved(s){$('#saveState').textContent=s;setTimeout(()=>{$('#saveState').textContent=''},2500)}
async function refreshState(){const r=await callApi('state',{group:session.group,participant:session.participant});if(r.state)server=r.state;renderParticipant()}
function renderParticipant(){const st=server.stage||1;$('#stageKicker').textContent=`Stage ${st} of ${STAGES.length}`;$('#stageTitle').textContent=STAGES[st-1].title;$('#stageContent').innerHTML=stageHtml(st);if(server.prompt){$('#promptBanner').textContent=`Thought prompt: ${server.prompt}`;$('#promptBanner').classList.remove('hidden')}else $('#promptBanner').classList.add('hidden');wireStage();startTimer()}
function startTimer(){clearInterval(timerHandle);const tick=()=>{if(!server.deadline){$('#timer').textContent='--:--';return}const left=Math.max(0,server.deadline-now()),m=Math.floor(left/60000),s=Math.floor((left%60000)/1000);$('#timer').textContent=`${m}:${String(s).padStart(2,'0')}`};tick();timerHandle=setInterval(tick,1000)}
async function initParticipant(){const groupSel=$('#groupId');groupSel.innerHTML=C.GROUPS.map(g=>`<option value="${g}">Group ${g}</option>`).join('');session.participant=localStorage.getItem('spark_participant')||'';session.group=localStorage.getItem('spark_group')||session.group;session.recorder=localStorage.getItem('spark_recorder')==='1';if(session.participant){$('#joinView').classList.add('hidden');$('#workshopView').classList.remove('hidden');await refreshState();pollHandle=setInterval(refreshState,C.POLL_MS)}else $('#joinBtn').onclick=async()=>{const p=$('#participantCode').value.trim();if(!p)return alert('Enter a participant code.');session.participant=p;session.group=$('#groupId').value;session.recorder=$('#isRecorder').checked;localStorage.setItem('spark_participant',p);localStorage.setItem('spark_group',session.group);localStorage.setItem('spark_recorder',session.recorder?'1':'0');await callApi('join',{participant:p,group:session.group,recorder:session.recorder});$('#joinView').classList.add('hidden');$('#workshopView').classList.remove('hidden');await refreshState();pollHandle=setInterval(refreshState,C.POLL_MS)}}
async function facilitatorState(){const r=await callApi('state',{group:session.group});server=r.state||server;renderFacilitator()}
function renderFacilitator(){const st=server.stage||1,ps=D.prompts[st]||[],votes=server.votes[`s${st}`]||{};$('#facilitatorView').innerHTML=`<div class="stagebar card compact"><div><div class="eyebrow">Facilitator · Group ${session.group}</div><h2>Stage ${st}: ${STAGES[st-1].title}</h2></div><div class="timerbox"><span class="timer-label">Time remaining</span><span id="timer">--:--</span></div></div><section class="card"><div class="fac-toolbar"><button class="ghost" id="prevStage">← Previous</button><button class="primary" id="nextStage">Advance stage →</button><button class="secondary-btn" id="plusMinute">+1 minute</button><button class="secondary-btn" id="resetTimer">Reset timer</button><select id="facGroup">${C.GROUPS.map(g=>`<option value="${g}" ${g===session.group?'selected':''}>Group ${g}</option>`).join('')}</select></div><div class="status-grid"><div class="metric"><strong>${server.participants?.length||0}</strong>participants</div><div class="metric"><strong>${server.ready?.length||0}</strong>ready</div><div class="metric"><strong>${server.selectedEvidence?.join(', ')||'—'}</strong>evidence</div><div class="metric"><strong>${Object.keys(votes).length}</strong>votes this stage</div></div></section><section class="card"><h3>Optional thought prompts</h3><p class="muted">Keep hidden unless the group is stalled, silent or reasoning superficially. Exposure is logged.</p><div class="fac-toolbar">${ps.map((p,i)=>`<button class="ghost showPrompt" data-prompt="${esc(p)}">Show ${i+1}: ${esc(p)}</button>`).join('')||'<span class="muted">No prompt scheduled for this stage.</span>'}<button class="ghost" id="hidePrompt">Hide prompt</button></div>${server.prompt?`<div class="prompt-banner">Visible now: ${esc(server.prompt)}</div>`:''}</section>${voteSummaryHtml(votes)}<section class="card"><h3>Private facilitator observation</h3><textarea id="facNote" placeholder="Confusion, prompting, spontaneous reasoning, claim calibration, timing, technology friction..."></textarea><button id="saveFacNote" class="secondary-btn">Save observation</button></section>`;startTimer();$('#facGroup').onchange=e=>{location.search=`?role=facilitator&group=${e.target.value}`};$('#nextStage').onclick=()=>facPatch({stage:Math.min(STAGES.length,st+1)});$('#prevStage').onclick=()=>facPatch({stage:Math.max(1,st-1)});$('#plusMinute').onclick=()=>facPatch({deadline:(server.deadline||now())+60000});$('#resetTimer').onclick=()=>facPatch({deadline:now()+STAGES[st-1].mins*60000});document.querySelectorAll('.showPrompt').forEach(b=>b.onclick=async()=>{await facPatch({prompt:b.dataset.prompt});await callApi('event',{group:session.group,event:'prompt_exposed',stage:st,prompt:b.dataset.prompt})});$('#hidePrompt').onclick=()=>facPatch({prompt:''});$('#saveFacNote').onclick=async()=>{await callApi('event',{group:session.group,event:'facilitator_note',stage:st,note:$('#facNote').value});alert('Observation saved')}}
async function facPatch(patch){await callApi('facilitator',{group:session.group,patch});await facilitatorState()}
function winnerText(votes){const dist=voteDistribution(votes),total=Object.keys(votes||{}).length;if(!total)return '—';const max=Math.max(...Object.values(dist)),wins=D.decisions.filter(x=>dist[x]===max&&max>0);return `${wins.join(' / ')} (${max}/${total})`}
async function renderSynthesis(){const r=await callApi('allState',{}),d=r.data||{},groups=C.GROUPS,stage=d.stage||1;const rows=groups.map(g=>{const vs=d.votes?.[g]||{},ev=(d.selectedEvidenceByGroup?.[g]||[]).join(', ')||'—';return `<tr><td>Group ${g}</td><td>${winnerText(vs.s1||{})}</td><td>${winnerText(vs.s5||{})}</td><td>${winnerText(vs.s6||{})}</td><td>${winnerText(vs.s8||{})}</td><td>${ev}</td></tr>`}).join('');const counts={};groups.forEach(g=>(d.selectedEvidenceByGroup?.[g]||[]).forEach(id=>counts[id]=(counts[id]||0)+1));const evSummary=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([id,n])=>`<span class="stakeholder">${id}: ${n} group${n===1?'':'s'}</span>`).join('')||'<span class="muted">No evidence selections yet.</span>';$('#synthesisView').innerHTML=`<div class="stagebar card compact"><div><div class="eyebrow">Cross-group synthesis</div><h2>SPARK Workshop 1</h2></div><span class="badge">Stage ${stage}</span></div><section class="card"><h3>Decision trajectories</h3><div class="table-wrap"><table><thead><tr><th>Group</th><th>Initial</th><th>Preliminary</th><th>After update</th><th>Final</th><th>Evidence selected</th></tr></thead><tbody>${rows}</tbody></table></div><p class="muted">Keep this view hidden from breakout groups until the scenario is complete.</p></section><section class="card"><h3>Evidence-selection pattern</h3><div class="stakeholders">${evSummary}</div></section>`}
(async function boot(){if(apiEnabled())$('#connectionBadge').textContent=appsScriptEnabled()?'Apps Script backend':'Connected backend';$('#roleBadge').textContent=session.role[0].toUpperCase()+session.role.slice(1);if(session.role==='participant'){await initParticipant()}else if(session.role==='facilitator'){$('#joinView').classList.add('hidden');$('#facilitatorView').classList.remove('hidden');await facilitatorState();pollHandle=setInterval(facilitatorState,C.POLL_MS)}else{$('#joinView').classList.add('hidden');$('#synthesisView').classList.remove('hidden');await renderSynthesis();pollHandle=setInterval(renderSynthesis,C.POLL_MS)}})();
