const C=window.SPARK_CONFIG||{};
const D=window.SPARK_DATA||{};
D.decisions=['Proceed under current requirements','Proceed with project-specific conditions','Defer pending specific studies/information','Oppose the project'];
if(Array.isArray(D.startingFacts)&&!D.startingFacts.some(x=>String(x).startsWith('Delay could reduce risk'))){D.startingFacts.push('Delay could reduce risk, but it could also mean losing the project and potential follow-on investment.');}
const GROUPS=C.GROUPS||['Owl','Fox','Raven','Dolphin','Octopus'];
const GROUP_META={Owl:'🦉',Fox:'🦊',Raven:'🐦‍⬛',Dolphin:'🐬',Octopus:'🐙'};
const STAGES=[{id:1,title:'Starting Record & Individual First Impression',mins:4},{id:2,title:'Need to Know',mins:6},{id:3,title:'Choose What to Investigate',mins:5},{id:4,title:'Review the Evidence',mins:8},{id:5,title:'Preliminary Group Recommendation',mins:7},{id:6,title:'Evolving Information Update',mins:5},{id:7,title:'Perspective Challenge',mins:6},{id:8,title:'Final Decision, Conditions & Reconsideration',mins:8},{id:9,title:'Reflection & Co-Design',mins:18},{id:10,title:'Transfer to Existing Instruction',mins:25}];
const MOD_GUIDE={
1:{say:'Please read the starting record and complete your first response individually before discussing it.',do:'Let everyone work independently. When the room is ready, move to the next phase.'},
2:{say:'Now compare your starting points and identify what you most need to know.',do:'Keep the discussion moving. Clarify instructions only. Do not suggest what they should notice.'},
3:{say:'Choose the two evidence areas you think would be most useful to this decision.',do:'Do not recommend evidence packets. Let the group choose.'},
4:{say:'Review what you selected and discuss what it answers and what remains uncertain.',do:'Keep attention on what the evidence actually supports.'},
5:{say:'Discuss your recommendation, then everyone should submit their own choice.',do:'Do not force consensus. Preserve disagreement, then advance when the room is ready.'},
6:{say:'Additional information is now available. Consider what, if anything, it changes.',do:'Do not imply that participants should change position.'},
7:{say:'Build the strongest case you can for the alternative shown on your screen.',do:'Encourage a serious case, not a straw man.'},
8:{say:'Make your final judgment and identify what would make it workable or cause you to reconsider.',do:'Preserve dissent. Do not push for agreement.'},
9:{say:'Now step out of the scenario and evaluate the experience as educators.',do:'Focus on authenticity, reasoning opportunities, scaffolds, observability and what should change.'},
10:{say:'Apply the same reasoning-opportunity lens to something you already teach or use.',do:'Keep the group concrete: existing activity, decision, uncertainty, evidence, minimal support and observable output.'}
};
const q=new URLSearchParams(location.search),REVIEW=q.get('review')==='1';
let session={role:REVIEW?'review':'participant',id:'',name:'',group:'',key:''};
let server={started:false,stage:1,deadline:null,serverNow:null,prompt:'',selectedEvidence:[],votes:{},groupData:{},participants:[],moderators:[]};
let viewStage=1,pollHandle=null,timerHandle=null,clockOffsetMs=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],now=()=>Date.now();
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function appsScriptEnabled(){return !!window.SPARK_APPS_SCRIPT&&typeof google!=='undefined'&&google.script&&google.script.run}
function apiEnabled(){return appsScriptEnabled()||!!C.API_URL}
function gas(action,payload={}){return new Promise((resolve,reject)=>google.script.run.withSuccessHandler(resolve).withFailureHandler(e=>reject(new Error(e?.message||e))).api(action,payload))}
async function callApi(action,payload={}){if(appsScriptEnabled())return gas(action,payload);if(C.API_URL){const r=await fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action,...payload})});if(!r.ok)throw new Error(`Backend ${r.status}`);return r.json()}return demoApi(action,payload)}
function groupLabel(g){return `${GROUP_META[g]||''} ${g}`.trim()}
function groupCards(){return `<div class="group-cards">${GROUPS.map(g=>`<button type="button" class="group-card" data-group="${esc(g)}"><span class="group-emoji">${GROUP_META[g]||''}</span><span>${esc(g)}</span></button>`).join('')}</div>`}
function blankControl(){return {started:false,stage:1,deadline:null,prompt:''}}
function demoKey(){return 'spark_workshop_v5_local'}
function demoLoad(){try{return JSON.parse(localStorage.getItem(demoKey())||'{}')}catch{return {}}}
function demoSave(d){localStorage.setItem(demoKey(),JSON.stringify(d))}
function demoPeople(d,g,role){return Object.values(d.people||{}).filter(x=>x.group===g&&x.role===role)}
async function demoApi(action,p={}){const d=demoLoad();d.controls=d.controls||{};d.people=d.people||{};d.votes=d.votes||{};d.groupData=d.groupData||{};d.events=d.events||[];const g=p.group||session.group||'Owl';d.controls[g]=d.controls[g]||blankControl();d.votes[g]=d.votes[g]||{};d.groupData[g]=d.groupData[g]||{};const c=d.controls[g];if(action==='join'){if(p.role==='moderator'&&p.key!==C.MODERATOR_KEY)return {ok:false,error:'Incorrect moderator code'};d.people[p.id]={id:p.id,name:p.name,group:g,role:p.role||'participant',ts:now()};if((p.role||'participant')==='participant'&&!c.started){c.started=true;c.stage=1;c.deadline=now()+STAGES[0].mins*60000;c.prompt=''}}if(action==='vote'){d.votes[g][`s${p.stage}`]=d.votes[g][`s${p.stage}`]||{};d.votes[g][`s${p.stage}`][p.id]={choice:p.choice,confidence:p.confidence,name:p.name,ts:now()}}if(action==='submit'){d.groupData[g][p.key]=p.value}if(action==='selectEvidence'){d.groupData[g].selectedEvidence=p.ids}if(action==='event')d.events.push({...p,ts:now()});if(action==='moderator'){if(p.key!==C.MODERATOR_KEY)return {ok:false,error:'Invalid moderator code'};const patch=p.patch||{};if('stage' in patch){c.stage=Math.max(1,Math.min(10,Number(patch.stage)||1));c.started=true;c.deadline=now()+STAGES[c.stage-1].mins*60000;c.prompt=''}if('deadline' in patch)c.deadline=patch.deadline;if('prompt' in patch)c.prompt=patch.prompt||''}demoSave(d);if(action==='state')return {ok:true,state:{serverNow:now(),...c,selectedEvidence:d.groupData[g].selectedEvidence||[],votes:d.votes[g]||{},groupData:d.groupData[g]||{},participants:demoPeople(d,g,'participant'),moderators:demoPeople(d,g,'moderator')}};return {ok:true}}
function decisionChoices(name){return `<div class="choice-grid">${D.decisions.map(x=>`<label class="choice"><input type="radio" name="${name}" value="${esc(x)}"><span>${esc(x)}</span></label>`).join('')}</div>`}
function confidence(id){return `<label>Confidence<div class="range-row"><input id="${id}" type="range" min="0" max="100" value="50"><span class="confidence-value" id="${id}v">50 / 100</span></div></label>`}
function tableRows(prefix,cols,rows=4){return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${Array.from({length:rows},(_,r)=>`<tr>${cols.map((_,c)=>`<td><textarea data-key="${prefix}_${r}_${c}"></textarea></td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function evidenceCard(id){const e=D.evidence?.[id];if(!e)return '';const facts=e.facts||[],unknowns=e.unknowns||[];return `<article class="evidence-card"><h4>${id}. ${esc(e.title)}</h4><div class="source-note"><strong>Quick read</strong></div><ul>${facts.slice(0,3).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><strong>Questions that still matter</strong><ul>${unknowns.slice(0,2).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${facts.length>3||unknowns.length>2?`<details><summary>More detail</summary>${facts.length>3?`<ul>${facts.slice(3).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${unknowns.length>2?`<strong>Other unresolved questions</strong><ul>${unknowns.slice(2).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<div class="source-note"><strong>Source status:</strong> ${esc(e.source||'')}</div></details>`:''}</article>`}
function selectedEvidenceHtml(){const ids=server.selectedEvidence||[];return ids.length?`<div class="evidence-grid">${ids.map(evidenceCard).join('')}</div>`:`<div class="callout">No evidence packets selected yet.</div>`}
function voteDistribution(votes){const out=Object.fromEntries(D.decisions.map(x=>[x,0]));Object.values(votes||{}).forEach(v=>{if(v&&out[v.choice]!==undefined)out[v.choice]++});return out}
function resultStatus(votes){const total=Object.keys(votes||{}).length;if(!total)return {label:'No submissions',choice:'',max:0,total,dist:voteDistribution(votes)};const dist=voteDistribution(votes),max=Math.max(...Object.values(dist)),wins=D.decisions.filter(x=>dist[x]===max&&max>0);if(max===total)return {label:'Consensus',choice:wins[0]||'',max,total,dist};if(wins.length===1&&max>total/2)return {label:'Strict majority',choice:wins[0],max,total,dist};return {label:'No majority / unresolved',choice:'',max,total,dist}}
function voteSummaryHtml(votes,hide=false){const r=resultStatus(votes);if(!r.total)return `<div class="card compact vote-summary"><p class="muted">No participant choices submitted yet.</p></div>`;if(hide)return `<div class="card compact vote-summary"><strong>${r.total}</strong> response${r.total===1?'':'s'} submitted.</div>`;return `<div class="card compact vote-summary"><div class="eyebrow">Current group result</div><p><strong>${r.label}${r.choice?`: ${esc(r.choice)}`:''}</strong>${r.choice?` (${r.max} of ${r.total})`:''}</p></div>`}
function currentGroupChoice(){return resultStatus(server.votes?.s6||{}).choice||resultStatus(server.votes?.s5||{}).choice||''}
function challengeFor(choice){if(choice===D.decisions[0]||choice===D.decisions[1])return D.decisions[2];if(choice===D.decisions[2]||choice===D.decisions[3])return D.decisions[1];return ''}
function collectScope(scope){const v={};scope.querySelectorAll('textarea[data-key]').forEach(el=>v[el.dataset.key]=el.value);scope.querySelectorAll('textarea[id],input[id],select[id]').forEach(el=>{if(!['radio','checkbox','button'].includes(el.type))v[el.id]=el.value});return v}
function startingPointsHtml(){const rows=Object.entries(server.groupData||{}).filter(([k,v])=>k.startsWith('s1_')&&v&&typeof v==='object').map(([k,v])=>({name:v.name||'Participant',factors:v.factors||'',unknown:v.unknown||''}));if(!rows.length)return '<p class="muted">Responses will appear as group members submit Phase 1.</p>';return `<div class="table-wrap"><table><thead><tr><th>Participant</th><th>Important factors</th><th>Important unknown</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.factors)}</td><td>${esc(r.unknown)}</td></tr>`).join('')}</tbody></table></div>`}
function allGroupVoted(stage){const joined=(server.participants||[]).length,submitted=Object.keys(server.votes?.[`s${stage}`]||{}).length;return joined>0&&submitted>=joined}
function ownVote(stage){return !!server.votes?.[`s${stage}`]?.[session.id]}
function stageHtml(n){if(n===1){const old=server.votes?.s1?.[session.id];const record=`<section class="card stage-card"><div class="callout"><strong>${groupLabel(session.group)}</strong> · Begin now. Complete your first response individually before discussing it.</div><h3>Your role</h3><p>You are part of a Community Advisory Team advising local leaders whether, and under what conditions, the community should support a proposed hyperscale data-center campus in Central Arkansas.</p><div class="instruction">Starting record: The following information is currently available to the Community Advisory Team.</div><div class="facts">${D.startingFacts.map(x=>`<div class="fact">${esc(x)}</div>`).join('')}</div></section>`;if(old)return `${record}<section class="card success-card"><h3>Response submitted ✓</h3><p><strong>${esc(old.choice)}</strong> · Confidence ${esc(old.confidence)}/100</p><p class="muted">Your response is recorded. Stay here until your moderator moves the group forward.</p></section>`;return `${record}<section class="card stage-card"><h3>Individual first impression</h3>${decisionChoices('s1decision')}${confidence('s1conf')}<label>Two or three factors most important to your recommendation<textarea id="s1factors"></textarea></label><label>Most important thing you still need to know or verify<textarea id="s1unknown"></textarea></label><button class="primary submit-vote" data-stage="1">Submit response</button></section>`}
if(n===2)return `<section class="card stage-card"><h3>Group starting points</h3><div id="liveStartingPoints">${startingPointsHtml()}</div></section><section class="card stage-card"><h3>Map uncertainty</h3><p>Compare questions and concerns. Distinguish supplied evidence from claims or assumptions that still need verification.</p>${tableRows('ntk',['Evidence we currently have','What we need to know / verify','How or where could we find out?'],4)}<label>Which 2–3 unanswered questions could most change the group's recommendation?<textarea id="priorityUnknowns"></textarea></label><button class="primary group-submit" data-key="stage2">Submit group response</button></section>`;
if(n===3)return `<section class="card stage-card"><h3>Choose only TWO evidence packets</h3><p>Choose based on what could change or sharpen the decision, not merely what sounds interesting.</p><div class="evidence-grid">${Object.entries(D.evidence||{}).map(([id,e])=>`<label class="evidence-card evidence-select"><input type="checkbox" name="evidence" value="${id}"><span><strong>${id}. ${esc(e.title)}</strong><br><span class="muted">${esc((e.unknowns||[])[0]||'')}</span></span></label>`).join('')}</div><label>Why these two?<textarea id="evidenceWhy"></textarea></label><label>What questions do you hope they answer?<textarea id="evidenceQuestions"></textarea></label><button class="primary" id="selectEvidenceBtn">Submit evidence choice</button></section>`;
if(n===4)return `<section class="card stage-card"><h3>Review the evidence</h3><p>Focus on what the evidence resolves, what it complicates and what remains uncertain.</p>${selectedEvidenceHtml()}</section><section class="card stage-card">${tableRows('review',['Packet','What did it help answer?','What remains uncertain / needs verification?','How useful was it?'],2)}<label>Did the evidence create any new important question?<textarea id="newQuestion"></textarea></label><button class="primary group-submit" data-key="stage4">Submit evidence review</button></section>`;
if(n===5)return `<section class="card stage-card"><h3>Preliminary group recommendation</h3><p>Discuss first. Then every participant submits a choice. A group result requires consensus or a strict majority (&gt;50%); otherwise it remains unresolved.</p>${decisionChoices('s5decision')}${confidence('s5conf')}<button class="primary submit-vote" data-stage="5">Submit individual choice</button></section>${voteSummaryHtml(server.votes?.s5||{},!allGroupVoted(5))}<section class="card stage-card"><label>Evidence that matters most<textarea id="s5evidence"></textarea></label><label>Why it matters / group reasoning<textarea id="s5reasoning"></textarea></label><label>Most important remaining uncertainty<textarea id="s5uncertainty"></textarea></label><label>Strongest dissenting rationale, if any<textarea id="s5dissent"></textarea></label><button class="primary group-submit" data-key="stage5">Submit group reasoning</button></section>`;
if(n===6)return `<section class="card stage-card"><h3>Evolving information update</h3><div class="instruction">Additional information becomes available. Some uncertainty is reduced while other uncertainty grows.</div><div class="facts">${D.stage6Update.map(x=>`<div class="fact">${esc(x)}</div>`).join('')}</div><p><strong>Does this information strengthen, weaken, or leave your recommendation unchanged?</strong></p>${decisionChoices('s6decision')}${confidence('s6conf')}<label>What changed in your reasoning, if anything?<textarea id="s6why"></textarea></label><label>What uncertainty matters most now?<textarea id="s6unknown"></textarea></label><button class="primary submit-vote" data-stage="6">Submit response</button></section>${voteSummaryHtml(server.votes?.s6||{},!allGroupVoted(6))}`;
if(n===7){const current=currentGroupChoice(),assigned=challengeFor(current);return `<section class="card stage-card"><h3>Perspective challenge</h3><p>Using only the evidence already available, construct the strongest defensible case for a plausible alternative to the group's current recommendation.</p>${assigned?`<div class="instruction">Current group result: <strong>${esc(current)}</strong><br>Assigned alternative: <strong>${esc(assigned)}</strong></div><input id="altChoice" type="hidden" value="${esc(assigned)}">`:`<label>Alternative recommendation<select id="altChoice"><option value="">Choose...</option>${D.decisions.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`}<label>Evidence that supports this alternative<textarea id="altEvidence"></textarea></label><label>Which stakeholder interest or risk does it take more seriously?<textarea id="altStakeholder"></textarea></label><label>What assumptions or enforceable conditions would have to be true?<textarea id="altConditions"></textarea></label><label>What is strongest about this alternative?<textarea id="altStrongest"></textarea></label><button class="primary group-submit" data-key="stage7">Submit perspective challenge</button></section>`}
if(n===8)return `<section class="card stage-card"><h3>Final individual choice</h3><p>After the evidence update and perspective challenge, every participant submits a final choice.</p>${decisionChoices('s8decision')}${confidence('s8conf')}<button class="primary submit-vote" data-stage="8">Submit individual choice</button></section>${voteSummaryHtml(server.votes?.s8||{},!allGroupVoted(8))}<section class="card stage-card"><h3>Make the decision implementable</h3>${tableRows('cond',['Condition / trigger','How measured or verified?','Who reports / enforces?','What happens if unmet?'],3)}<label>What future evidence/event/condition would make the group reconsider?<textarea id="reconsider"></textarea></label><label>What new information would NOT be enough by itself?<textarea id="notEnough"></textarea></label><label>Strongest dissenting rationale, if any<textarea id="finalDissent"></textarea></label><button class="primary group-submit" data-key="stage8">Submit final group artifact</button></section>`;
if(n===9)return `<section class="card stage-card"><h3>Reflection & co-design</h3><p>Now step out of the scenario and evaluate the experience as educators.</p><label>Authenticity & usability: What felt realistic or artificial? What must change?<textarea id="rAuthenticity"></textarea></label><label>Reasoning opportunities: Where did meaningful reasoning happen? What emerged without being explicitly prompted?<textarea id="rReasoning"></textarea></label><label>Scaffolds & cognitive load: What helped, constrained, led or confused?<textarea id="rScaffolds"></textarea></label><label>Observability: What student work or behavior could a teacher realistically collect or observe?<textarea id="rObservable"></textarea></label><button class="primary group-submit" data-key="stage9">Submit reflection</button></section>`;
if(n===10)return `<section class="card stage-card"><h3>Transfer to existing instruction</h3><p>Identify one activity you already use and apply the same reasoning-opportunity lens.</p><label>Existing activity<textarea id="tActivity"></textarea></label><label>Consequential judgment or decision students make<textarea id="tDecision"></textarea></label><label>What is uncertain / incomplete?<textarea id="tUncertainty"></textarea></label><label>What evidence could matter?<textarea id="tEvidence"></textarea></label><label>Minimal change that could strengthen the reasoning opportunity<textarea id="tMinimal"></textarea></label><label>What could a teacher realistically observe?<textarea id="tObserve"></textarea></label><label>Where else could the same reasoning pattern transfer?<textarea id="tTransfer"></textarea></label><button class="primary group-submit" data-key="stage10">Submit transfer map</button></section>`;return ''}
function draftKey(){return `spark_draft_${session.id}_${session.group}_${viewStage}`}
function saveDraft(){if(session.role!=='participant')return;const root=$('#stageContent');if(!root)return;const d={};root.querySelectorAll('textarea,input,select').forEach(el=>{const k=el.id||el.dataset.key||el.name;if(!k)return;if(el.type==='radio'){if(el.checked)d[`r:${el.name}`]=el.value}else if(el.type==='checkbox'){d[`c:${el.value}`]=el.checked}else d[k]=el.value});localStorage.setItem(draftKey(),JSON.stringify(d))}
function restoreDraft(){if(session.role!=='participant')return;let d={};try{d=JSON.parse(localStorage.getItem(draftKey())||'{}')}catch{};const root=$('#stageContent');if(!root)return;Object.entries(d).forEach(([k,v])=>{if(k.startsWith('r:')){const el=root.querySelector(`input[name="${CSS.escape(k.slice(2))}"][value="${CSS.escape(v)}"]`);if(el)el.checked=true}else if(k.startsWith('c:')){const el=[...root.querySelectorAll('input[type=checkbox]')].find(x=>x.value===k.slice(2));if(el)el.checked=!!v}else{const el=root.querySelector(`#${CSS.escape(k)}`)||root.querySelector(`[data-key="${CSS.escape(k)}"]`);if(el)el.value=v}});$$('input[type=range]').forEach(x=>{const v=$('#'+x.id+'v');if(v)v.textContent=`${x.value} / 100`})}
function clearDraft(stage=viewStage){localStorage.removeItem(`spark_draft_${session.id}_${session.group}_${stage}`)}
function syncViewToServer(){if(REVIEW)return;if(server.stage>viewStage){if(session.role==='participant'&&[1,5,6,8].includes(viewStage)&&!ownVote(viewStage))return;viewStage=server.stage;localStorage.setItem(`spark_stage_${session.id}`,viewStage)}else if(viewStage>server.stage)viewStage=server.stage}
function syncedNow(){return now()+clockOffsetMs}
function startTimer(){clearInterval(timerHandle);const tick=()=>{const el=$('#timer');if(!el)return;if(!server.deadline){el.textContent='--:--';return}const left=Math.max(0,server.deadline-syncedNow()),m=Math.floor(left/60000),s=Math.floor((left%60000)/1000);el.textContent=`${m}:${String(s).padStart(2,'0')}`};tick();timerHandle=setInterval(tick,1000)}
function moderatorOverlayHtml(){if(session.role!=='moderator')return '';const st=server.stage||1,guide=MOD_GUIDE[st],pcount=server.participants?.length||0,vcount=Object.keys(server.votes?.[`s${st}`]||{}).length,progress=[1,5,6,8].includes(st)?`${vcount}/${pcount} submitted`:phaseProgressHtml(st);return `<section class="card compact" id="moderatorOverlay"><div class="fac-toolbar" style="align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap"><strong>Moderator · ${groupLabel(session.group)} · ${esc(progress)}</strong><span><button class="secondary-btn" id="plusMinute">+1 min</button> <button class="primary" id="nextStage" ${st>=10?'disabled':''}>${st<10?'Next phase →':'Final phase'}</button></span></div><details style="margin-top:8px"><summary>Guide</summary><div class="instruction" style="margin-top:8px"><strong>SAY</strong><br>${esc(guide.say)}</div><div class="source-note"><strong>DO</strong><br>${esc(guide.do)}</div></details></section>`}
function renderParticipant(scroll=false){syncViewToServer();$('#workshopView').classList.remove('hidden');$('#stageKicker').textContent=`Phase ${viewStage} of ${STAGES.length} · ${groupLabel(session.group)}`;$('#stageTitle').textContent=STAGES[viewStage-1].title;$('#stageContent').innerHTML=moderatorOverlayHtml()+stageHtml(viewStage);if(server.prompt){$('#promptBanner').textContent=`Thought prompt: ${server.prompt}`;$('#promptBanner').classList.remove('hidden')}else $('#promptBanner').classList.add('hidden');wireStage();restoreDraft();if(session.role==='moderator'){const content=$('#stageContent');content.querySelectorAll('.stage-card input,.stage-card textarea,.stage-card select,.stage-card button').forEach(el=>el.disabled=true);$('#plusMinute')?.addEventListener('click',()=>moderatorPatch({deadline:(server.deadline||syncedNow())+60000}));$('#nextStage')?.addEventListener('click',()=>moderatorPatch({stage:Math.min(10,(server.stage||1)+1)}));}startTimer();if(scroll)scrollTo({top:0,behavior:'smooth'})}
function wireDrafts(){if(session.role!=='participant')return;const root=$('#stageContent');root.querySelectorAll('textarea,input,select').forEach(el=>{el.addEventListener('input',saveDraft);el.addEventListener('change',saveDraft)})}
function wireStage(){wireDrafts();$$('input[type=range]').forEach(x=>x.oninput=()=>{const v=$('#'+x.id+'v');if(v)v.textContent=`${x.value} / 100`;saveDraft()});if(session.role!=='participant')return;$$('.submit-vote').forEach(b=>b.onclick=async()=>{const st=+b.dataset.stage,choice=$(`input[name=s${st}decision]:checked`)?.value;if(!choice)return alert('Choose a recommendation first.');const conf=+($(`#s${st}conf`)?.value||50);b.disabled=true;b.textContent='Submitting…';await callApi('vote',{group:session.group,id:session.id,name:session.name,stage:st,choice,confidence:conf});if(st===1)await callApi('submit',{group:session.group,id:session.id,key:`s1_${session.id}`,value:{name:session.name,factors:$('#s1factors')?.value||'',unknown:$('#s1unknown')?.value||''}});if(st===6)await callApi('submit',{group:session.group,id:session.id,key:`s6_${session.id}`,value:{name:session.name,why:$('#s6why')?.value||'',unknown:$('#s6unknown')?.value||''}});clearDraft(st);await fetchState(true)});$$('.group-submit').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Submitting…';await callApi('submit',{group:session.group,id:session.id,key:b.dataset.key,value:{...collectScope(b.closest('section')),submittedBy:session.name}});clearDraft();await fetchState(true)});$('#selectEvidenceBtn')?.addEventListener('click',async e=>{const b=e.currentTarget,ids=$$('input[name=evidence]:checked').map(x=>x.value);if(ids.length!==2)return alert('Choose exactly two evidence packets.');b.disabled=true;b.textContent='Submitting…';await callApi('selectEvidence',{group:session.group,id:session.id,ids});await callApi('submit',{group:session.group,id:session.id,key:'stage3',value:{ids,why:$('#evidenceWhy')?.value||'',questions:$('#evidenceQuestions')?.value||'',submittedBy:session.name}});clearDraft();await fetchState(true)})}
async function moderatorPatch(patch){const r=await callApi('moderator',{group:session.group,key:session.key,patch});if(r&&!r.ok)return alert(r.error||'Moderator action failed.');await fetchState(true)}
async function fetchState(forceRender=false){const requestAt=now(),r=await callApi('state',{group:session.group,id:session.id}),responseAt=now();if(!r?.state)return;const oldStage=server.stage,oldDeadline=server.deadline;if(Number.isFinite(Number(r.state.serverNow))){const midpoint=(requestAt+responseAt)/2;clockOffsetMs=Number(r.state.serverNow)-midpoint}server=r.state;syncViewToServer();if(forceRender||server.stage!==oldStage){renderParticipant(server.stage!==oldStage);return}if(server.deadline!==oldDeadline)startTimer();if(viewStage===2){const box=$('#liveStartingPoints');if(box)box.innerHTML=startingPointsHtml()}if([5,6,8].includes(viewStage)){const card=$('.vote-summary');if(card){const holder=document.createElement('div');holder.innerHTML=voteSummaryHtml(server.votes?.[`s${viewStage}`]||{},!allGroupVoted(viewStage));card.replaceWith(holder.firstElementChild)}}if(session.role==='moderator'){const overlay=$('#moderatorOverlay');if(overlay){const holder=document.createElement('div');holder.innerHTML=moderatorOverlayHtml();overlay.replaceWith(holder.firstElementChild);$('#plusMinute')?.addEventListener('click',()=>moderatorPatch({deadline:(server.deadline||syncedNow())+60000}));$('#nextStage')?.addEventListener('click',()=>moderatorPatch({stage:Math.min(10,(server.stage||1)+1)}));}}}
function setGroupSelection(root,group){root.querySelectorAll('.group-card').forEach(b=>b.classList.toggle('selected',b.dataset.group===group))}
function phaseProgressHtml(st){const ps=server.participants?.length||0,v=Object.keys(server.votes?.[`s${st}`]||{}).length,gd=server.groupData||{};if([1,6].includes(st))return `${v}/${ps} submitted`;if(st===2)return gd.stage2?'Group response submitted':'Group response pending';if(st===3)return gd.stage3?'Evidence choice submitted':'Evidence choice pending';if(st===4)return gd.stage4?'Evidence review submitted':'Evidence review pending';if(st===5)return `${v}/${ps} choices · ${gd.stage5?'reasoning submitted':'reasoning pending'}`;if(st===7)return gd.stage7?'Challenge submitted':'Challenge pending';if(st===8)return `${v}/${ps} choices · ${gd.stage8?'artifact submitted':'artifact pending'}`;if(st===9)return gd.stage9?'Reflection submitted':'Reflection pending';return gd.stage10?'Transfer map submitted':'Transfer map pending'}
async function initEntry(){session.id=localStorage.getItem('spark_id')||((crypto&&crypto.randomUUID)?crypto.randomUUID():`p_${Date.now()}`);localStorage.setItem('spark_id',session.id);session.name=localStorage.getItem('spark_name')||'';session.group=localStorage.getItem('spark_group')||'';session.role=localStorage.getItem('spark_role')||'participant';session.key=localStorage.getItem('spark_mod_key')||'';$('#participantName').value=session.name;$('#entryRole').value=session.role;$('#moderatorCodeWrap').classList.toggle('hidden',session.role!=='moderator');$('#moderatorCode').value=session.role==='moderator'?session.key:'';$('#groupCards').innerHTML=groupCards();if(session.group)setGroupSelection($('#groupCards'),session.group);$$('#groupCards .group-card').forEach(b=>b.onclick=()=>{session.group=b.dataset.group;setGroupSelection($('#groupCards'),session.group)});$('#entryRole').onchange=e=>{$('#moderatorCodeWrap').classList.toggle('hidden',e.target.value!=='moderator')};const enter=async()=>{const r=await callApi('join',{id:session.id,name:session.name,group:session.group,role:session.role,key:session.key});if(!r?.ok)return alert(r?.error||'Could not join.');$('#joinView').classList.add('hidden');$('#roleBadge').textContent=session.role==='moderator'?'Moderator':'Teacher / Player';await fetchState(true);viewStage=server.stage||1;renderParticipant(false);pollHandle=setInterval(()=>fetchState(false),C.POLL_MS||2000)};$('#joinBtn').onclick=async()=>{const name=$('#participantName').value.trim(),role=$('#entryRole').value,key=$('#moderatorCode').value.trim();if(!name)return alert('Enter your full name.');if(!session.group)return alert('Select the breakout group assigned to you.');if(role==='moderator'&&key!==C.MODERATOR_KEY)return alert('Enter the correct moderator code.');session.name=name;session.role=role;session.key=role==='moderator'?key:'';localStorage.setItem('spark_name',name);localStorage.setItem('spark_group',session.group);localStorage.setItem('spark_role',role);if(role==='moderator')localStorage.setItem('spark_mod_key',key);else localStorage.removeItem('spark_mod_key');await enter()};}
function renderReview(){session.name='Reviewer';session.id='reviewer';session.group='Owl';session.role='review';server={serverNow:now(),started:true,stage:1,deadline:now()+240000,prompt:'',selectedEvidence:['A','B'],participants:[{id:'1',name:'Sample Teacher 1',role:'participant'},{id:'2',name:'Sample Teacher 2',role:'participant'}],moderators:[],votes:{},groupData:{}};$('#joinView').classList.add('hidden');$('#roleBadge').textContent='Review';const ctl=document.createElement('section');ctl.className='card review-controls';ctl.innerHTML=`<strong>Core educator / PI review</strong><div class="fac-toolbar"><button class="ghost" id="reviewPrev">← Previous</button><select id="reviewStage">${STAGES.map(s=>`<option value="${s.id}">${s.id}. ${esc(s.title)}</option>`).join('')}</select><button class="primary" id="reviewNext">Next →</button></div>`;$('#workshopView').classList.remove('hidden');$('#workshopView').prepend(ctl);const go=n=>{viewStage=Math.max(1,Math.min(10,n));server.stage=viewStage;server.deadline=now()+STAGES[viewStage-1].mins*60000;$('#reviewStage').value=viewStage;renderParticipant(false)};$('#reviewPrev').onclick=()=>go(viewStage-1);$('#reviewNext').onclick=()=>go(viewStage+1);$('#reviewStage').onchange=e=>go(+e.target.value);go(1)}
(async function boot(){$('#connectionBadge').textContent=apiEnabled()?(appsScriptEnabled()?'Live backend':'Connected backend'):'Local test mode';if(REVIEW){renderReview();return}await initEntry()})();