export const SCENARIO = {
  title: "Data Center Decision Under Uncertainty",
  subtitle: "SPARK Workshop Scenario Player",
  tabs: [
    {id:"first-impression",label:"1. First Impression",minutes:5,title:"First Impression",intro:"Community decisions often begin before all relevant information is available.",body:["A technology infrastructure developer is proposing a large AI data center in a central Arkansas community.","The proposed project represents approximately $1 billion in initial investment.","The first facility would be approximately 300,000 square feet.","The project is expected to create substantial construction employment.","Approximately 50 permanent jobs are currently anticipated.","Approximately 160 acres are associated with the proposed development area.","The project includes substantial long-term property-tax incentives.","Additional data-center buildings could potentially be developed in the future.","Several infrastructure and implementation details are still being developed."],responseType:"initial"},
    {id:"need-to-know",label:"2. Need to Know",minutes:6,title:"What do we need to know?",intro:"Identify the unanswered questions that could affect your recommendation.",body:["Individually identify the three most important unanswered questions that could affect your recommendation.","Then discuss your questions with your group. Combine similar questions, identify which matter most, discuss why they matter, and consider where useful evidence might come from.","Possible sources include city records, utility information, planning documents, technical experts, project developers, independent studies, community members, and state or federal agencies."],responseType:"questions"},
    {id:"investigate",label:"3. Investigate",minutes:7,title:"Decide what to investigate",intro:"Your group has limited time before providing its preliminary recommendation.",body:["Select two information areas and explain why they matter."],options:["Economic benefits and tax structure","Electricity and grid requirements","Cooling water and wastewater","Infrastructure and public costs","Land use and planning","Community concerns","Developer and end-user information"],responseType:"investigation"},
    {id:"evidence",label:"4. Evidence",minutes:10,title:"Review the information",intro:"Review the available information. Previous tabs remain available.",packets:[
      {key:"Economic benefits and tax structure",text:"The project represents approximately $1 billion in proposed initial investment and approximately 50 permanent jobs, in addition to temporary construction employment. The proposed economic-development arrangement includes substantial property-tax incentives over an extended period. The project could produce additional local and regional economic activity. However, the eventual net public benefit depends partly on the final incentive agreement, infrastructure responsibilities, operating impacts, and whether additional development occurs."},
      {key:"Electricity and grid requirements",text:"A large data center requires substantial electrical service. Current project planning anticipates utility infrastructure for the initial facility. Larger future electrical requirements may require additional coordination and potentially significant infrastructure investment. Some questions about long-term capacity, future expansion, infrastructure needs, responsibility for costs, and possible effects on other utility customers remain unresolved in the currently available information."},
      {key:"Cooling water and wastewater",text:"Current planning contemplates using treated wastewater or effluent as part of the cooling system rather than relying solely on drinking water. Additional pumping and pipeline infrastructure would be required. A separate discharge or blowdown system may also be necessary. Some final operating quantities, infrastructure requirements, and implementation details remain under development."},
      {key:"Infrastructure and public costs",text:"The project may require roadway modifications, utility improvements, new pipelines, pumping infrastructure, and other supporting systems. Responsibility for the timing and financing of some infrastructure improvements is still being negotiated. The project could therefore create both economic benefits and infrastructure obligations."},
      {key:"Land use and planning",text:"The proposed development area has been evaluated for industrial use. Planning analysis found the proposed land use generally compatible with surrounding development and considered expected traffic effects manageable within the scope of that review. However, land-use approval does not itself answer broader questions about utilities, fiscal effects, environmental impacts, or long-term community consequences."},
      {key:"Community concerns",text:"Community members have raised questions about electricity capacity and possible rate impacts, water and wastewater, environmental effects, transparency, the pace of decision making, economic benefits, and the eventual operator of the facility. These concerns identify issues residents believe require attention. However, a concern by itself does not establish how large or likely an impact will be."},
      {key:"Developer and end-user information",text:"The project development entity is publicly identifiable. The eventual major technology user has not been fully disclosed publicly. Some details about future operations, expansion, resource requirements, and operating practices therefore remain difficult to independently evaluate from the currently available information."}],responseType:"evidence-review"},
    {id:"preliminary",label:"5. Preliminary",minutes:8,title:"Preliminary recommendation",intro:"Make a preliminary recommendation using the information currently available.",responseType:"recommendation"},
    {id:"new-information",label:"6. New Information",minutes:6,title:"New information",intro:"Your group now receives additional information.",body:["The proposed initial facility may not represent the full eventual development.","Existing project arrangements contemplate the possibility of additional data-center buildings if future conditions support expansion.","Some infrastructure timing and financing arrangements remain under negotiation.","Decisions made regarding the initial project could therefore influence a substantially larger future development.","Do not assume that new information automatically requires changing your position."],responseType:"update"},
    {id:"final",label:"7. Reconsider",minutes:5,title:"Final recommendation and reconsideration",intro:"Make your current recommendation and identify what could reopen it later.",responseType:"final"}
  ]
};
export const RECOMMENDATIONS=["Proceed","Proceed with conditions","Defer pending more information","Oppose"];
